### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by majornorth** [Pushwoosh/pushwoosh-phonegap-cordova-sample#2]
Hey, thanks for putting this up! I was hoping to get better insight into how to setup Pushswoosh for Ionic, as the API documentation is pretty scarce, but it's pretty difficult for somebody new to the platform to understand what's going on here.

What is PushwooshWP.js for? WordPress? 
Update: I see now that it's for Win32NT? I 

Also, why isn't there an .onDeviceReady where I register my app_id for iOS?
Update: I also see that this is further down in the function. For some reason my page search didn't return this the first time I looked.

All the same, a readme would be helpful :)

Thanks!

**Comment by stewartmccoy** [comment]
So, my goal is to send a push notifications from the Pushwoosh control panel and receive it in an app loaded with Ionic View. 

On the Pushwoosh Control Panel I added a new application. I also set up and app id and provisioning profile on my Apple Dev account and made sure that the id in the config.xml was the same used for the provision profile (I had to make a new one because the one in the cloned code was already registered). I imported this info to Pushwoosh.

I cloned the repo to local, cd into Ionic, changed the app_id in PushwooshiOS.js on line 41 to corresponded to the application code  on my control panel for the application I created.

Also, there no was no mention in the API docs that I need to add a device—although once I saw it in the sidebar (with ~30 other links...), then it seemed obvious. But now I'm trying to figure out how to alert the device token when the app is deployed via Ionic View.

Anyway, I'm pretty lost. Thanks for understanding.

**Comment by shaders** [comment]
What add device are you talking about? I don't understand what is the issue from the text above. Please try to explain the problem.

![image](https://cloud.githubusercontent.com/assets/1770540/12479698/bcc469f0-c05e-11e5-91e0-56ce9a21146a.png)

**Comment by stewartmccoy** [comment]
I'm sorry if my original post was unclear.

However, I think it would be tremendously helpful if there was a readme that documented how to get going with each build. For example, with iOS, I would love to know how which parts of the code I need to customize (e.g. app_id and device token), as well as what I need to do to set up a test notification form the Pushwoosh Control Panel. These steps are not at all clear and I have not been able to accomplish this task despite spending 4 hours on it. If this is the case for most Pushwoosh developers, then Pushwoosh is losing a lot of potential paying customers.

**Comment by stewartmccoy** [comment]
Anyway, I'm giving up and going to give Parse a shot.

**Comment by shaders** [comment]
You can find extensive guides here:
http://docs.pushwoosh.com/
http://docs.pushwoosh.com/docs/cordova-phonegap

Also here:
https://rawgit.com/Pushwoosh/pushwoosh-phonegap-plugin/master/Documentation/files/PushNotification-js.html

**Comment by majornorth** [comment]
Yep! I've already read the cordova-phonegap docs several times. I haven't seen the rawgit link yet, but I'll review that. I realize that part of my troubles could just be particular to using Ionic and Ionic View. Thanks again.
